# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a176ae934bd4f7c4abeb307d4cae95e7c97b35f84653f455cacae1a7d8c35d5f23a09ef40b9b784f5896a3b48ec93cc232a4d268d9694ad611d2ec2113a89ca1

test:
  secret_key_base: d2f758d20cfd63a15878a931cbf379e2338f06c47b7c306795e1778a00d6723bc047168672b9c9ee18692c34c1948e2ecf2630188af3bd21b7acd1f2ca319bdc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
